name: "ГБПОУ РО \"Сальский индустриальный техникум\""
short_name: "СИТ"
full_name: "Государственное бюджетное профессиональное образовательное учреждение Ростовской области \"Сальский индустриальный техникум\""
description: "Официальный сайт ГБПОУ РО \"Сальский индустриальный техникум\" (СИТ) — подготовка специалистов среднего звена по техническим и экономическим специальностям. г. Сальск, Ростовская область."
url: "https://сит-сальск.рф"
legacy_url: "https://sit-salsk.ru"
address: "347630, Ростовская область, г. Сальск, ул. Ленина, д. 27 (Корпус №1)"
phone: "+7 (86372) 5-05-71"
phone_link: "tel:+78637250571"
email: "sitsalsk@mail.ru"
director: "Сенченко Марина Евгеньевна"
working_hours: "Пн–Пт: 8:00–17:00 | Сб, Вс: выходной"
founded: 1978
copyright: "2026"
license: "№Л035-01276-61/00201708 (рег. №5923 от 09.10.2020)"
accreditation: "№А007-01276-61/01000428 от 18.06.2019"
social:
  vk: "https://vk.com/sitsalsksit"
  rutube: "https://rutube.ru/channel/24197012/"
